# Site settings
title: mth2610.github.io
email: mth2610@gmail.com
author: mth2610
description: "Blog của Thắng, viết về những gì mà Thắng thích :)"
baseurl: ""
url: "http://mth2610.github.io"
twitter_username: mth2610
github_username:  mth2610
linkedin_username: mth2610

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

gems:
  - jekyll-sitemap
